"""initial schema

Adopts Alembic for a database whose tables were previously created by
db.create_all(), so it has to be safe in three situations:

  * a brand new database               -> everything is created
  * one deployed before refresh tokens -> refresh_tokens and
                                          users.sessions_valid_from are added
  * one already fully up to date       -> nothing happens

Every step is guarded by an inspector check, so `flask db upgrade` is safe to
run against a live database and never drops or rewrites existing rows. Later
migrations can be plain autogenerated ones — this guarding is only needed for
the changeover away from create_all().

Revision ID: 7aba98760412
Revises:
Create Date: 2026-08-17 11:35:15.142639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '7aba98760412'
down_revision = None
branch_labels = None
depends_on = None


def _inspector():
    return inspect(op.get_bind())


def _has_table(name):
    return name in _inspector().get_table_names()


def _has_column(table, column):
    return column in {c["name"] for c in _inspector().get_columns(table)}


def _create_users():
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('password_hash', sa.LargeBinary(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def _create_idempotency_keys():
    op.create_table(
        'idempotency_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=128), nullable=False),
        sa.Column('endpoint', sa.String(length=64), nullable=False),
        sa.Column('request_hash', sa.String(length=64), nullable=False),
        sa.Column('status_code', sa.Integer(), nullable=False),
        sa.Column('response_body', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id', 'key', 'endpoint', name='uq_idempotency_user_key_endpoint'
        ),
    )
    op.create_index(
        op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False
    )


def _create_refresh_tokens():
    op.create_table(
        'refresh_tokens',
        sa.Column('jti', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('family_id', sa.String(length=36), nullable=False),
        sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('jti'),
    )
    op.create_index(
        op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False
    )
    op.create_index(
        op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False
    )
    op.create_index(
        op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False
    )


def _create_revoked_tokens():
    op.create_table(
        'revoked_tokens',
        sa.Column('jti', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('jti'),
    )
    op.create_index(
        op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False
    )


def _create_statements():
    op.create_table(
        'statements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=32), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('row_count', sa.Integer(), nullable=False),
        sa.Column('total_income', sa.Float(), nullable=False),
        sa.Column('total_expenses', sa.Float(), nullable=False),
        sa.Column('period_start', sa.Date(), nullable=True),
        sa.Column('period_end', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'token', name='uq_statement_user_token'),
    )
    op.create_index(op.f('ix_statements_token'), 'statements', ['token'], unique=False)
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)


def _create_transactions():
    op.create_table(
        'transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('statement_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('description', sa.String(length=512), nullable=False),
        sa.Column('category', sa.String(length=64), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('kind', sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_kind'), 'transactions', ['kind'], unique=False)
    op.create_index(
        op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False
    )
    op.create_index(
        'ix_transactions_user_date', 'transactions', ['user_id', 'date'], unique=False
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)


# Order matters: users must exist before anything that references it, and
# statements before transactions.
_TABLES = [
    ('users', _create_users),
    ('idempotency_keys', _create_idempotency_keys),
    ('refresh_tokens', _create_refresh_tokens),
    ('revoked_tokens', _create_revoked_tokens),
    ('statements', _create_statements),
    ('transactions', _create_transactions),
]


def upgrade():
    for name, create in _TABLES:
        if not _has_table(name):
            create()

    # A database deployed before refresh tokens has `users` but not this column.
    if not _has_column('users', 'sessions_valid_from'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(
                sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True)
            )


def downgrade():
    """Drop every table.

    This destroys all financial data. It exists so the migration is reversible
    in development and must never be run against production.
    """
    for name, _ in reversed(_TABLES):
        if _has_table(name):
            op.drop_table(name)
